---
load_config_file: __path_to(root/forms/defaults.yml)__
attrs:
  class: site-configuration

elements:
  - type: Fieldset
    attrs:
      class: secondCol
    elements:
      - type: Text
        name: name
        label_loc: Site name
        filters:
          - HTMLEscape
        constraints:
          - Required
      - type: Text
        name: admins
        label_loc: Site Admins (In addition to you)
      - type: Text
        name: anonymous_user
        label_loc: Anonymous User (blank to disable)
      - type: Select
        name: theme
        label_loc: Theme name
      - type: Select
        name: main_formatter
        label_loc: Main formatter
        options:
          - [ 'MojoMojo::Formatter::Markdown', 'Markdown' ]
          - [ 'MojoMojo::Formatter::Textile',  'Textile'  ]
      - type: Checkbox
        name: open_registration
        label_loc: New User Registration open
        value: 1
        default_empty_value: 0
      - type: Checkbox
        name: use_captcha
        label_loc: Use captcha
        value: 1
        default_empty_value: 0
      - type: Checkbox
        name: disable_search
        value: 1
        default_empty_value: 0
        label_loc: Disable internal search (use Google)
      - type: Checkbox
        name: enable_emoticons
        label_loc: Enable graphical emoticons
        value: 1
        default_empty_value: 0
  - type: Fieldset
    elements:
      - type: Checkbox
        name: restricted_user
        value: 1
        default_empty_value: 0
        label_loc: Restrict user editing to home directory
      - type: Checkbox
        name: enforce_login
        value: 1
        default_empty_value: 0
        label_loc: Enforce login
      - type: Checkbox
        name: check_permission_on_view
        value: 1
        default_empty_value: 0
        label_loc: Check permission on view
      - type: Checkbox
        name: cache_permission_data
        value: 1
        default_empty_value: 0
        label_loc: Cache permission data
      - type: Checkbox
        name: create_allowed
        value: 1
        default_empty_value: 0
        label_loc: Create allowed by default
      - type: Checkbox
        name: delete_allowed
        value: 1
        default_empty_value: 0
        label_loc: Delete allowed by default
      - type: Checkbox
        name: edit_allowed
        value: 1
        default_empty_value: 0
        label_loc: Edit allowed by default
      - type: Checkbox
        name: view_allowed
        value: 1
        default_empty_value: 0
        label_loc: View allowed by default
      - type: Checkbox
        name: attachment_allowed
        value: 1
        default_empty_value: 0
        label_loc: Attachment allowed by default
  - type: Submit
    name: submit
    value_loc: Save
